// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWeek8.EF;

namespace TestWeek8.EF.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20211029090535_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestWeek8.Core.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Menu di Capodanno"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Menu di Natale"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Menu di Pasqua"
                        });
                });

            modelBuilder.Entity("TestWeek8.Core.Models.Piatto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prezzo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("Piatti");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MenuId = 1,
                            Nome = "Tortelloni di ricotta ed erbe di campo",
                            Prezzo = 9.90m,
                            Tipo = "Primo"
                        },
                        new
                        {
                            Id = 2,
                            MenuId = 1,
                            Nome = "Lasagne ai funghi",
                            Prezzo = 11m,
                            Tipo = "Primo"
                        },
                        new
                        {
                            Id = 3,
                            MenuId = 1,
                            Nome = "Stinco di maiale al forno",
                            Prezzo = 11.5m,
                            Tipo = "Secondo"
                        },
                        new
                        {
                            Id = 4,
                            MenuId = 1,
                            Nome = "Spiedini di gamberi al cumino",
                            Prezzo = 12m,
                            Tipo = "Secondo"
                        },
                        new
                        {
                            Id = 5,
                            MenuId = 1,
                            Nome = "Verza all'aceto",
                            Prezzo = 6.5m,
                            Tipo = "Contorno"
                        },
                        new
                        {
                            Id = 6,
                            MenuId = 1,
                            Nome = "Funghi champignon al forno",
                            Prezzo = 7m,
                            Tipo = "Contorno"
                        },
                        new
                        {
                            Id = 7,
                            MenuId = 1,
                            Nome = "Meringhe al cacao e alla nocciola",
                            Prezzo = 5.9m,
                            Tipo = "Dolce"
                        },
                        new
                        {
                            Id = 8,
                            MenuId = 1,
                            Nome = "Zuppa inglese",
                            Prezzo = 4m,
                            Tipo = "Dolce"
                        },
                        new
                        {
                            Id = 9,
                            MenuId = 2,
                            Nome = "Anelletti al forno",
                            Prezzo = 10m,
                            Tipo = "Primo"
                        },
                        new
                        {
                            Id = 10,
                            MenuId = 2,
                            Nome = "Crespelle al nero di seppia e salmone",
                            Prezzo = 11.5m,
                            Tipo = "Primo"
                        },
                        new
                        {
                            Id = 11,
                            MenuId = 2,
                            Nome = "Gamberoni al forno",
                            Prezzo = 11.9m,
                            Tipo = "Secondo"
                        },
                        new
                        {
                            Id = 12,
                            MenuId = 2,
                            Nome = "Rollatine di pollo alla Wellington",
                            Prezzo = 9m,
                            Tipo = "Secondo"
                        },
                        new
                        {
                            Id = 13,
                            MenuId = 2,
                            Nome = "Zucca al forno con arancia e pepe",
                            Prezzo = 7m,
                            Tipo = "Contorno"
                        },
                        new
                        {
                            Id = 14,
                            MenuId = 2,
                            Nome = "Patate ventaglio al forno",
                            Prezzo = 5m,
                            Tipo = "Contorno"
                        },
                        new
                        {
                            Id = 15,
                            MenuId = 2,
                            Nome = "Cassata al forno",
                            Prezzo = 5.5m,
                            Tipo = "Dolce"
                        },
                        new
                        {
                            Id = 16,
                            MenuId = 2,
                            Nome = "Babà napoletano",
                            Prezzo = 6m,
                            Tipo = "Dolce"
                        },
                        new
                        {
                            Id = 17,
                            MenuId = 3,
                            Nome = "Tagliolini al ragù di agnello",
                            Prezzo = 11.9m,
                            Tipo = "Primo"
                        },
                        new
                        {
                            Id = 18,
                            MenuId = 3,
                            Nome = "Pasta al forno con funghi, prosciutto e piselli",
                            Prezzo = 10.9m,
                            Tipo = "Primo"
                        },
                        new
                        {
                            Id = 19,
                            MenuId = 3,
                            Nome = "Costine di agnello al sugo",
                            Prezzo = 13m,
                            Tipo = "Secondo"
                        },
                        new
                        {
                            Id = 20,
                            MenuId = 3,
                            Nome = "Anelli di calamari al forno",
                            Prezzo = 13.5m,
                            Tipo = "Secondo"
                        },
                        new
                        {
                            Id = 21,
                            MenuId = 3,
                            Nome = "Cavoletti di bruxelles arrosto con salsa di sesamo e limone",
                            Prezzo = 7.9m,
                            Tipo = "Contorno"
                        },
                        new
                        {
                            Id = 22,
                            MenuId = 3,
                            Nome = "Rotolo al cocco con crema di cioccolato",
                            Prezzo = 8.5m,
                            Tipo = "Dolce"
                        },
                        new
                        {
                            Id = 23,
                            MenuId = 3,
                            Nome = "Crostatine con chantilly al torrone",
                            Prezzo = 6.9m,
                            Tipo = "Dolce"
                        });
                });

            modelBuilder.Entity("TestWeek8.Core.Models.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utenti");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "diego.scano@abc.it",
                            Password = "1234",
                            Ruolo = "Ristoratore"
                        },
                        new
                        {
                            Id = 2,
                            Email = "mario.rossi@abc.it",
                            Password = "5678",
                            Ruolo = "Cliente"
                        });
                });

            modelBuilder.Entity("TestWeek8.Core.Models.Piatto", b =>
                {
                    b.HasOne("TestWeek8.Core.Models.Menu", "Menu")
                        .WithMany("Piatti")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("TestWeek8.Core.Models.Menu", b =>
                {
                    b.Navigation("Piatti");
                });
#pragma warning restore 612, 618
        }
    }
}
